import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "../_shared/cors.ts";
import {
  getExtractionWarning,
  isValidExtraction,
  mergeExtractions,
  processExtraction,
} from "./postProcessing.ts";

const conditionFields = [
  "Liquidity Sweep",
  "MSS",
  "FVG",
  "Displacement",
  "Order Block",
  "Stochastic Confirmation",
];

const conditionValues = [
  "NOT DETECTED",
  "CONFIDENT",
  "LIKELY",
  "UNCERTAIN",
];

function jsonResponse(body: Record<string, unknown>, status: number) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function errorResponse(code: string, detail: string, status: number) {
  return jsonResponse({ error: code, detail }, status);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasExactStringFields(
  value: unknown,
  fields: string[],
): value is Record<string, string> {
  if (!isRecord(value)) {
    return false;
  }

  const keys = Object.keys(value);
  return keys.length === fields.length && fields.every(
    (field) => keys.includes(field) && typeof value[field] === "string",
  );
}

function isValidConditionStates(value: unknown): value is Record<string, string> {
  return hasExactStringFields(value, conditionFields) && conditionFields.every(
    (field) => conditionValues.includes(value[field]),
  );
}

function getImageDataUrl(body: unknown): string | null {
  if (!isRecord(body) || typeof body.image !== "string" || !body.image.trim()) {
    return null;
  }

  const image = body.image.trim();
  if (image.startsWith("data:image/") && image.includes(";base64,")) {
    return image;
  }

  if (/^[A-Za-z0-9+/]+=*$/.test(image)) {
    const mimeType = typeof body.mimeType === "string" && body.mimeType.startsWith("image/")
      ? body.mimeType
      : "image/png";
    return `data:${mimeType};base64,${image}`;
  }

  return null;
}

async function authenticate(request: Request): Promise<boolean> {
  const authorization = request.headers.get("Authorization");
  const hasAuthorizationHeader = Boolean(authorization);
  const hasBearerPrefix = Boolean(authorization?.startsWith("Bearer "));
  console.log("auth header present:", hasAuthorizationHeader);
  console.log("auth header starts with Bearer:", hasBearerPrefix);

  if (!hasBearerPrefix) {
    console.error("auth rejected: missing or invalid Authorization scheme");
    return false;
  }

  const token = authorization.slice("Bearer ".length).trim();
  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY");
  const hasSupabaseUrl = Boolean(supabaseUrl);
  const hasSupabaseAnonKey = Boolean(supabaseAnonKey);
  console.log("SUPABASE_URL defined:", hasSupabaseUrl);
  console.log("SUPABASE_ANON_KEY defined:", hasSupabaseAnonKey);

  if (!token || !supabaseUrl || !supabaseAnonKey) {
    console.error("auth rejected: token or Supabase auth configuration missing");
    return false;
  }

  const supabase = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  console.log("calling supabase.auth.getUser");
  const { data, error } = await supabase.auth.getUser(token);
  console.log("supabase.auth.getUser error:", error ? { message: error.message, status: error.status } : null);
  console.log("supabase.auth.getUser returned user:", Boolean(data.user));
  return !error && Boolean(data.user);
}

function visionPrompt(description: string) {
  return `Here is a literal description of what's visible on this chart, generated by examining the image first:

---
${description}
---

Use this description together with the image itself to extract the following JSON, applying the priority rules below. Where the description distinguishes the current price ticker from position tool levels, respect that distinction — never use the current price ticker's value for Entry, Stop Loss, or Take Profit.

Extract trade data using this strict priority order. Only use a signal from a HIGHER tier; if a tier gives no evidence, do not fall back to guessing from a lower-confidence visual pattern — leave the field empty instead.

TIER 1 (highest confidence): explicit text label next to a price line/box/row. Synonyms: 'TP'/'Take Profit'/'Target'/'Limit' = Take Profit. 'SL'/'Stop Loss'/'Stop' = Stop Loss. 'Entry'/'Open' = Entry.

TIER 2 — POSITION TOOL (color-independent): identify by MEANING: STOP LOSS = level with NEGATIVE dollar amount (a loss if hit). TAKE PROFIT = level with POSITIVE, FIXED-target dollar amount. Colors may correlate but NEVER rely on color alone — confirm via sign-of-P&L. Read exact price from the axis for each; match crowded/stacked labels carefully.

For VARIANT A (two-zone + callout): Entry is a distinct origin/boundary marker's price where the two zones meet or originate — read from the description's explicit answer to this. It is NEVER the current price ticker's value, even if they happen to be numerically close or identical. If the description did not identify a distinct entry marker separate from the ticker, leave Entry empty rather than using the ticker value.

If the description identifies a small marker icon (circle/dot/arrow) as a distinct point, treat its price as Entry, with the same confidence as any other origin marker.

For VARIANT B (row list): Entry is the middle row's own price value, read from the axis at that row's specific price level — not its dollar amount. Ensure this price was captured in the description; if not clearly identified, leave Entry empty.

FOR DIRECTION: extract independently as best-effort — explicit 'Buy'/'Long'/'Sell'/'Short' text (highest confidence), or a directional arrow icon (up arrow = Buy/Long, down arrow = Sell/Short) as secondary. If neither visible, empty string. This may be overridden by code when Entry/SL/TP are all known — that's expected.

If Risk/Reward ratio isn't directly shown but Entry, Stop Loss, and Take Profit are all confidently known, note in your response that it can be computed (the exact calculation will happen in code, not by you) — return your best direct read of any shown ratio, or empty string if none is shown and let the code calculate it.

For Position Size: only use a number with an explicit label containing 'Size', 'Qty', 'Quantity', 'Lots', 'Units', or 'Contracts'. Never use a generic 'Amount' label. Otherwise empty string.

For P&L: only use a distinctly and unambiguously labeled 'P&L', 'Profit', or 'Net P&L' figure that is NOT simply a risk or reward amount tied to a Stop Loss or Take Profit zone. Otherwise empty string.

TIER 3 (no evidence): If neither Tier 1 nor Tier 2 applies — even if there are colored price boxes on the axis, trend lines, moving averages, support/resistance lines, or session/swing markers that might look like trade levels — return empty string for Entry, Stop Loss, and Take Profit. Do not guess from proximity, color alone, or 'it looks like a stop loss'.

For the separate top-level 'currentPrice' field: read the current/live price if clearly visible (often bold, near the symbol name, or highlighted on the price axis), as a plain number. Otherwise empty string. Read date and time only from clearly visible date/time labels; never infer them from price-pattern matching.

Return only strict JSON matching this exact schema, with no markdown or extra keys:
{
  "extraction": {
    "asset": "", "direction": "", "entry": "", "exit": "", "stopLoss": "", "takeProfit": "", "pnl": "", "date": "", "time": "", "timeframe": "", "positionSize": "", "riskReward": "", "strategy": ""
  },
  "conditionStates": {
    "Liquidity Sweep": "NOT DETECTED", "MSS": "NOT DETECTED", "FVG": "NOT DETECTED", "Displacement": "NOT DETECTED", "Order Block": "NOT DETECTED", "Stochastic Confirmation": "NOT DETECTED"
  },
  "currentPrice": ""
}

For exit, fill only a distinct, clearly labeled closing or exit price; otherwise leave it empty. Use empty strings when the required evidence is absent, and never invent values.

For each setup condition, use CONFIDENT, LIKELY, UNCERTAIN, or NOT DETECTED based on how clearly the visual evidence matches these definitions — never mark CONFIDENT without clear supporting evidence:

Order Block: the last candle in the OPPOSITE direction of a move, immediately preceding a strong displacement in the other direction (bullish OB = last down-close/bearish candle right before a strong up-move; bearish OB = last up-close/bullish candle right before a strong down-move). Often drawn as a highlighted rectangle on the origin candle.

FVG (Fair Value Gap): a three-candle pattern where a strong displacement candle (candle 2) leaves a gap of unfilled price between candle 1 and candle 3 — the high of candle 1 doesn't overlap the low of candle 3 (bullish), or vice versa (bearish). Often drawn as a shaded box/zone, sometimes explicitly labeled 'FVG'.

MSS (Market Structure Shift): price sweeps liquidity past a prior swing high or low (a brief spike beyond it), THEN reverses and breaks the OPPOSING prior swing point with a strong-bodied candle CLOSE (not just a wick) — signaling a trend/structure change.

Displacement: a sudden, wide-range, strong-bodied directional candle or short sequence of candles that breaks market structure aggressively — noticeably larger/faster than surrounding price action, typically leaving an FVG behind.

Liquidity Sweep: price briefly spikes beyond a recent swing high/low, equal highs/lows, or a clearly marked horizontal level, with a wick poking through it, before reversing back — indicates a stop-hunt.

Stochastic Confirmation: ONLY applicable if a Stochastic oscillator panel is visible on the chart (a lower sub-panel with two lines oscillating 0-100). Confirmed when the %K line crosses the %D line INSIDE the overbought zone (above 80) for a Short/Sell trade, or INSIDE the oversold zone (below 20) for a Long/Buy trade, matching the trade's direction. If no Stochastic panel is visible at all, always return NOT DETECTED — never guess this from other indicators.`;
}

function descriptionPrompt() {
  return `Describe exactly what trade-related information is visible on this chart image, in plain text. Be specific and literal about what you see, not what you infer. Cover:
1. CURRENT PRICE TICKER: Is there a price/percentage display near the symbol name (usually top-left, distinct from any chart drawing)? What value does it show? This is the live market price, NOT a trade level — describe it separately from anything below.
2. POSITION/ORDER TOOL: Is there a position or order visualization on the chart? If yes, describe its EXACT structure: how many distinct colored rows/zones/boxes are there, what text or numbers are attached to each one (quantity, dollar amount, sign), and their relative vertical order/price positions. For EVERY zone, row, or level you identify in the position tool (including any that might represent the entry/origin point), you MUST report its exact price value read from the price axis — not just quantity or dollar amount. If a row's price isn't clearly readable from the axis, say so explicitly rather than omitting it. Do not interpret which is Entry/SL/TP yet — just describe what's literally visible.
3. ENTRY/ORIGIN MARKER: Separately from the current price ticker, is there a distinct entry/origin marker for the position — for example, a small circle, dot, arrow, or the boundary point where two colored zones meet or originate? If so, describe its exact price value. If no such distinct marker exists and only the current price ticker is visible, say so explicitly — do not assume the ticker IS the entry marker.
Additionally, look specifically for small marker icons that might indicate a trade's entry point: small circles, dots, or arrow icons (especially near where colored zones begin or where candlesticks are annotated). These are often small and subtle. If you find one, describe its exact price value from the axis. If genuinely none is visible even after looking carefully, say so explicitly.
4. EXPLICIT LABELS: Are there any text words reading 'TP', 'SL', 'Entry', 'Take Profit', 'Stop Loss', 'Buy', 'Sell', 'Long', or 'Short' anywhere on the chart? Quote them and describe their exact location.
5. CHART PATTERNS: Describe any visible candlestick patterns, drawn zones, or labels that might relate to order blocks, fair value gaps, structure breaks, or liquidity sweeps — describe what's drawn/labeled, not your interpretation of ICT theory.
6. OTHER: date/time labels, timeframe indicator, asset/symbol name.`;
}

async function requestDescription(imageDataUrl: string, apiKey: string, model: string) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20_000);

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        temperature: 0,
        messages: [{
          role: "user",
          content: [
            { type: "text", text: descriptionPrompt() },
            { type: "image_url", image_url: { url: imageDataUrl, detail: "high" } },
          ],
        }],
      }),
    });

    if (!response.ok) {
      return { error: `OpenAI returned HTTP ${response.status}.` };
    }

    const payload = await response.json();
    const content = payload?.choices?.[0]?.message?.content;
    return typeof content === "string" && content.trim()
      ? { content }
      : { error: "OpenAI returned no description content." };
  } catch (error) {
    return { error: error instanceof Error && error.name === "AbortError" ? "OpenAI description request timed out." : "OpenAI description request failed." };
  } finally {
    clearTimeout(timeout);
  }
}

async function requestVision(imageDataUrl: string, apiKey: string, model: string, description: string) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20_000);

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        temperature: 0,
        response_format: { type: "json_object" },
        messages: [{
          role: "user",
          content: [
            { type: "text", text: visionPrompt(description) },
            { type: "image_url", image_url: { url: imageDataUrl, detail: "high" } },
          ],
        }],
      }),
    });

    if (!response.ok) {
      return { error: `OpenAI returned HTTP ${response.status}.` };
    }

    const payload = await response.json();
    const content = payload?.choices?.[0]?.message?.content;
    return typeof content === "string" ? { content } : { error: "OpenAI returned no message content." };
  } catch (error) {
    return { error: error instanceof Error && error.name === "AbortError" ? "OpenAI request timed out." : "OpenAI request failed." };
  } finally {
    clearTimeout(timeout);
  }
}

Deno.serve(async (request) => {
  console.log("request received:", { method: request.method, authorizationHeaderPresent: Boolean(request.headers.get("Authorization")) });

  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return errorResponse("METHOD_NOT_ALLOWED", "Only POST requests are supported.", 405);
  }

  if (!(await authenticate(request))) {
    return errorResponse("AUTH_REQUIRED", "A valid Supabase access token is required.", 401);
  }

  const apiKey = Deno.env.get("OPENAI_API_KEY");
  console.log("OPENAI_API_KEY diagnostics:", {
    defined: Boolean(apiKey),
    length: apiKey?.length ?? 0,
    startsWithSk: apiKey?.startsWith("sk-") ?? false,
  });
  if (!apiKey) {
    return errorResponse("OPENAI_NOT_CONFIGURED", "OPENAI_API_KEY is not configured.", 500);
  }

  const model = Deno.env.get("OPENAI_VISION_MODEL") || "gpt-4o-mini";
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return errorResponse("INVALID_REQUEST", "Request body must be valid JSON.", 400);
  }

  const imageDataUrl = getImageDataUrl(body);
  if (!imageDataUrl) {
    return errorResponse("IMAGE_REQUIRED", "Provide a base64 image in the image field.", 400);
  }

  const descriptionResult = await requestDescription(imageDataUrl, apiKey, model);
  if ("error" in descriptionResult) {
    return errorResponse("VISION_DESCRIPTION_FAILED", descriptionResult.error, 502);
  }

  const visionResults = await Promise.all([
    requestVision(imageDataUrl, apiKey, model, descriptionResult.content),
    requestVision(imageDataUrl, apiKey, model, descriptionResult.content),
  ]);
  const failedVisionResult = visionResults.find((result) => "error" in result);
  if (failedVisionResult && "error" in failedVisionResult) {
    return errorResponse("VISION_REQUEST_FAILED", failedVisionResult.error, 502);
  }

  const parsedResults = visionResults.map((visionResult) => {
    try {
      const parsed: unknown = JSON.parse(visionResult.content);
      if (!isRecord(parsed) || !isValidExtraction(parsed.extraction) || !isValidConditionStates(parsed.conditionStates)) {
        return { error: "OpenAI response did not match the canonical screenshot schema." };
      }
      return { parsed };
    } catch {
      return { error: "OpenAI returned malformed JSON." };
    }
  });
  const parseError = parsedResults.find((result) => "error" in result);
  if (parseError && "error" in parseError) {
    return errorResponse(
      parseError.error === "OpenAI returned malformed JSON." ? "VISION_PARSE_FAILED" : "VISION_SCHEMA_INVALID",
      parseError.error,
      502,
    );
  }

  const firstParsed = parsedResults[0].parsed;
  const secondParsed = parsedResults[1].parsed;
  const merged = mergeExtractions(
    firstParsed.extraction,
    secondParsed.extraction,
    firstParsed.conditionStates,
    secondParsed.conditionStates,
  );
  const currentPrice = typeof firstParsed.currentPrice === "string" ? firstParsed.currentPrice : "";
  const finalExtraction = processExtraction(merged.extraction, currentPrice);

  return jsonResponse({
    extraction: finalExtraction,
    conditionStates: merged.conditionStates,
    model,
    warning: getExtractionWarning(merged.hasMismatch),
  }, 200);
});